---
title: "short amplicon sequencing analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r setup, include=FALSE}
library(dplyr)
library(tibble)
library(ggpubr)
library(RVAideMemoire)
library(ggplot2)
library(vegan)
library(reshape)
knitr::opts_chunk$set(echo = TRUE)
```

# mock sequencing results evaluated with expected results

```{r}
Data <- read.table("mock.csv", sep = ",", header = T, row.names = 1)
```
```{r}
data.matrix = as.matrix(Data[c("expected", "detected")])
data.matrix
G.test(data.matrix)
```
# pooled G-test
```{r}
Total.R = sum(Data$expected)                           # Set up data for pooled
Total.L = sum(Data$detected)                           #   G-test

observed = c(Total.R, Total.L)
expected = c(0.5, 0.5)

G.test(x=observed,
       p=expected)
```

#TOTAL G-test
```{r}
Total.G = sum(Data$G)
Total.df = sum(Data$df)
Total.G
Total.df
pchisq(Total.G,
       df = Total.df,
       lower.tail = FALSE)
```

# Procrustes and permutation analysis
```{r}
sample_PE200 <- read.table("sample_PE200.csv", sep = ",", header = T, row.names = 1)
sample_SE400 <- read.table("sample_SE400.csv", sep = ",", header = T, row.names = 1)
```

```{r}
dist_PE200 <- vegdist(sample_PE200, method = "bray")
nmds_PE200 <- metaMDS(dist_PE200, k=2, trymax = 20)
dist_SE400 <- vegdist(sample_SE400, method = "bray")
nmds_SE400 <- metaMDS(dist_SE400, k=2, trymax = 20)

pro <- procrustes(nmds_MiSeq, nmds_PE200)
pro
plot(pro, kind = 1, choices = c(1,2), to.target = TRUE, type = "p", xlab = "Dimention1", ylab = "Dimention2", ar.col = "blue", len = 0.05, cex = 0.7)
protest(nmds_MiSeq, nmds_PE200, scores = "sites", permutations = 999)
plot(pro,kind = 2)
```

# NMDS analysis for all three plots

```{r}
data <- read.csv("all.csv", sep = ",", header = T, row.names = 1) 
```
```{r}
data <- as.data.frame(internal2)
data <- as.numeric(data)
dist_data <- vegdist(data, method = "bray")
nmds_data <- metaMDS(dist_data, k=2, trymax = 20)
qdat_data <- as.data.frame(nmds_data$points)
ggplot(qdat_data, aes(x=MDS1, y=MDS2, colour = plot, shape = group))+geom_point()+scale_color_manual(values=c("#C6FFDD", "#FBD786", "#f7797d"))
```

# PERMANOVA analysis for technical replicates
```{r}
tech <- read.table("tech_OTU.csv", sep = ",", header = T, row.names = 1)
tech2 <- read.table("tech_info.csv", sep = ",", header = T, row.names = 1)
```

```{r}
a <- adonis(tech ~ Plot, data = tech2, permutations = 999, method = "bray")
a
a2 <- adonis(tech ~ Plat, data = tech2, permutations = 999, method = "bray")
a2 
a3 <- adonis(tech ~ PCR, data = tech2, permutations = 999, method = "bray")
a3 
a4 <- adonis(tech ~ RUN, data = tech2, permutations = 999, method = "bray")
a4
```

# Kruskal-Wallis test and alpha diversity analysis

```{r}
misqe <- read.table("MiSeq.txt",header = T,row.names = 1,sep = "\t")
pe200 <- read.table("PE200.txt",header = T,row.names = 1,sep = "\t")
se400 <- read.table("SE400.txt",header = T,row.names = 1,sep = "\t")
```

```{r}
misqe[misqe < 10] <- 0
pe200[pe200 < 10] <- 0
se400[se400 < 10] <- 0

misqe_rev <- misqe %>% t() %>% as.data.frame()
pe200_rev <- pe200 %>% t() %>% as.data.frame()
se400_rev <- se400 %>% t() %>% as.data.frame()
richness_miseq <- rowSums(misqe_rev > 0) %>% as.data.frame() %>% rownames_to_column("Sample_name")# %>% rename(Richness=".")
richness_pe200 <- rowSums(pe200_rev > 0) %>% as.data.frame() %>% rownames_to_column("Sample_name")# %>% rename(Richness=".")
richness_se400 <- rowSums(se400_rev > 0) %>% as.data.frame() %>% rownames_to_column("Sample_name")# %>% rename(Richness=".")

bac_count_rev <- se400_rev
richness <- rowSums(bac_count_rev > 0) %>% as.data.frame() %>% rownames_to_column("Sample_names")# %>% rename(richness=".")
richness_tmp <- rowSums(bac_count_rev > 0)
shannon_index <- diversity(bac_count_rev, index = 'shannon', base = exp(1)) %>% as.data.frame()# %>% rename(shannon_index=".")
shannon_index_tmp <- diversity(bac_count_rev, index = 'shannon', base = exp(1))
shannon_diversity <- exp(1)^shannon_index_tmp %>% as.data.frame()# %>% rename(shannon_diversity=".")
pielou <- (shannon_index_tmp / log(richness_tmp, exp(1))) %>% as.data.frame()# %>% rename(pielou=".")
gini_simpson_index <- diversity(bac_count_rev, index = 'simpson') %>% as.data.frame()# %>% rename(gini_simpson_index=".")
gini_simpson_index_tmp <- diversity(bac_count_rev, index = 'simpson')
simpson_index <- (1 - gini_simpson_index_tmp) %>% as.data.frame()# %>% rename(simpson_index=".")
invsimpson_index <- (1 / gini_simpson_index_tmp) %>% as.data.frame()# %>% rename(invsimpson_index=".")
simpson_diversity <- (1 / (1 - gini_simpson_index_tmp)) %>% as.data.frame()# %>% rename(simpson_diversity=".")
equitability <- (1 / (richness_tmp * (1 - gini_simpson_index_tmp))) %>% as.data.frame()# %>% rename(equitability=".")
chao1 <- estimateR(bac_count_rev)[2, ] %>% as.data.frame()# %>% rename(Chao1=".")
ace <- estimateR(bac_count_rev)[4, ] %>% as.data.frame()# %>% rename(ace=".")
richness_se400 <- cbind(richness,shannon_index,shannon_diversity,pielou,gini_simpson_index,simpson_index,invsimpson_index,simpson_diversity,chao1,ace,equitability)
colnames(richness_se400) <- c("Sample_names","Richness","Shannon_index","Shannon_diversity","Pielou","Gini_simpson_index","Simpson_index","Invsimpson_index","Simpson_diversity","Chao1","Ace","Equitability")

bac_count_rev <- pe200_rev
richness <- rowSums(bac_count_rev > 0) %>% as.data.frame() %>% rownames_to_column("Sample_names")# %>% rename(richness=".")
richness_tmp <- rowSums(bac_count_rev > 0)
shannon_index <- diversity(bac_count_rev, index = 'shannon', base = exp(1)) %>% as.data.frame()# %>% rename(shannon_index=".")
shannon_index_tmp <- diversity(bac_count_rev, index = 'shannon', base = exp(1))
shannon_diversity <- exp(1)^shannon_index_tmp %>% as.data.frame()# %>% rename(shannon_diversity=".")
pielou <- (shannon_index_tmp / log(richness_tmp, exp(1))) %>% as.data.frame()# %>% rename(pielou=".")
gini_simpson_index <- diversity(bac_count_rev, index = 'simpson') %>% as.data.frame()# %>% rename(gini_simpson_index=".")
gini_simpson_index_tmp <- diversity(bac_count_rev, index = 'simpson')
simpson_index <- (1 - gini_simpson_index_tmp) %>% as.data.frame()# %>% rename(simpson_index=".")
invsimpson_index <- (1 / gini_simpson_index_tmp) %>% as.data.frame()# %>% rename(invsimpson_index=".")
simpson_diversity <- (1 / (1 - gini_simpson_index_tmp)) %>% as.data.frame()# %>% rename(simpson_diversity=".")
equitability <- (1 / (richness_tmp * (1 - gini_simpson_index_tmp))) %>% as.data.frame()# %>% rename(equitability=".")
chao1 <- estimateR(bac_count_rev)[2, ] %>% as.data.frame()# %>% rename(Chao1=".")
ace <- estimateR(bac_count_rev)[4, ] %>% as.data.frame()# %>% rename(ace=".")
richness_pe200 <- cbind(richness,shannon_index,shannon_diversity,pielou,gini_simpson_index,simpson_index,invsimpson_index,simpson_diversity,chao1,ace,equitability)
colnames(richness_pe200) <- c("Sample_names","Richness","Shannon_index","Shannon_diversity","Pielou","Gini_simpson_index","Simpson_index","Invsimpson_index","Simpson_diversity","Chao1","Ace","Equitability")

bac_count_rev <- misqe_rev
richness <- rowSums(bac_count_rev > 0) %>% as.data.frame() %>% rownames_to_column("Sample_names")# %>% rename(richness=".")
richness_tmp <- rowSums(bac_count_rev > 0)
shannon_index <- diversity(bac_count_rev, index = 'shannon', base = exp(1)) %>% as.data.frame()# %>% rename(shannon_index=".")
shannon_index_tmp <- diversity(bac_count_rev, index = 'shannon', base = exp(1))
shannon_diversity <- exp(1)^shannon_index_tmp %>% as.data.frame()# %>% rename(shannon_diversity=".")
pielou <- (shannon_index_tmp / log(richness_tmp, exp(1))) %>% as.data.frame()# %>% rename(pielou=".")
gini_simpson_index <- diversity(bac_count_rev, index = 'simpson') %>% as.data.frame()# %>% rename(gini_simpson_index=".")
gini_simpson_index_tmp <- diversity(bac_count_rev, index = 'simpson')
simpson_index <- (1 - gini_simpson_index_tmp) %>% as.data.frame()# %>% rename(simpson_index=".")
invsimpson_index <- (1 / gini_simpson_index_tmp) %>% as.data.frame()# %>% rename(invsimpson_index=".")
simpson_diversity <- (1 / (1 - gini_simpson_index_tmp)) %>% as.data.frame()# %>% rename(simpson_diversity=".")
equitability <- (1 / (richness_tmp * (1 - gini_simpson_index_tmp))) %>% as.data.frame()# %>% rename(equitability=".")
chao1 <- estimateR(bac_count_rev)[2, ] %>% as.data.frame()# %>% rename(Chao1=".")
ace <- estimateR(bac_count_rev)[4, ] %>% as.data.frame()# %>% rename(ace=".")
richness_miseq <- cbind(richness,shannon_index,shannon_diversity,pielou,gini_simpson_index,simpson_index,invsimpson_index,simpson_diversity,chao1,ace,equitability)
colnames(richness_miseq) <- c("Sample_names","Richness","Shannon_index","Shannon_diversity","Pielou","Gini_simpson_index","Simpson_index","Invsimpson_index","Simpson_diversity","Chao1","Ace","Equitability")

if(do.write){
  write.csv(richness_miseq,file = "shannon_index_miseq.csv",row.names = F)
}

rich_als_miseq_name <- grep("^ALS",richness_miseq$Sample_name,value = T)
rich_als_miseq <- richness_miseq %>% filter(richness_miseq$Sample_name %in% c(rich_als_miseq_name))
rich_lj_miseq_name <- grep("^LJ",richness_miseq$Sample_name,value = T)
rich_lj_miseq <- richness_miseq %>% filter(richness_miseq$Sample_name %in% c(rich_lj_miseq_name))
rich_nbh_miseq_name <- grep("^NBH",richness_miseq$Sample_name,value = T)
rich_nbh_miseq <- richness_miseq %>% filter(richness_miseq$Sample_name %in% c(rich_nbh_miseq_name))

rich_als_pe200_name <- grep("^ALS",richness_pe200$Sample_name,value = T)
rich_als_pe200 <- richness_pe200 %>% filter(richness_pe200$Sample_name %in% c(rich_als_pe200_name))
rich_lj_pe200_name <- grep("^LJ",richness_pe200$Sample_name,value = T)
rich_lj_pe200 <- richness_pe200 %>% filter(richness_pe200$Sample_name %in% c(rich_lj_pe200_name))
rich_nbh_pe200_name <- grep("^NBH",richness_pe200$Sample_name,value = T)
rich_nbh_pe200 <- richness_pe200 %>% filter(richness_pe200$Sample_name %in% c(rich_nbh_pe200_name))

rich_als_se400_name <- grep("^ALS",richness_se400$Sample_name,value = T)
rich_als_se400 <- richness_se400 %>% filter(richness_se400$Sample_name %in% c(rich_als_se400_name))
rich_lj_se400_name <- grep("^LJ",richness_se400$Sample_name,value = T)
rich_lj_se400 <- richness_se400 %>% filter(richness_se400$Sample_name %in% c(rich_lj_se400_name))
rich_nbh_se400_name <- grep("^NBH",richness_se400$Sample_name,value = T)
rich_nbh_se400 <- richness_se400 %>% filter(richness_se400$Sample_name %in% c(rich_nbh_se400_name))

rich_als_miseq$Method <- "MiSeq"
rich_als_miseq$Site <- "ALS"
rich_als_pe200$Method <- "PE200"
rich_als_pe200$Site <- "ALS"
rich_als_se400$Method <- "SE400"
rich_als_se400$Site <- "ALS"

rich_lj_miseq$Method <- "MiSeq"
rich_lj_miseq$Site <- "LJ"
rich_lj_pe200$Method <- "PE200"
rich_lj_pe200$Site <- "LJ"
rich_lj_se400$Method <- "SE400"
rich_lj_se400$Site <- "LJ"

rich_nbh_miseq$Method <- "MiSeq"
rich_nbh_miseq$Site <- "NBH"
rich_nbh_pe200$Method <- "PE200"
rich_nbh_pe200$Site <- "NBH"
rich_nbh_se400$Method <- "SE400"
rich_nbh_se400$Site <- "NBH"

rich_als <- rbind(rich_als_miseq,rich_als_pe200,rich_als_se400)
rich_lj <- rbind(rich_lj_miseq,rich_lj_pe200,rich_lj_se400)
rich_nbh <- rbind(rich_nbh_miseq,rich_nbh_pe200,rich_nbh_se400)

rich_all <- rbind(rich_als,rich_lj,rich_nbh)

rich_all_melt <- melt(rich_all, measure.vars = c("Chao1","Shannon_diversity","Simpson_diversity","Equitability","Richness","Ace"),variable.name = "method",value.name = "index")

ggplot(data=rich_all_melt, aes(x=Site,y=value))+ 
  geom_boxplot(aes(fill=Method)) + 
  facet_grid(variable~Site, scales="free") + 
  scale_fill_manual(values=c("#C6FFDD", "#FBD786", "#f7797d", "#6dd5ed", "#F3A183"),name = "Methods") + 
  stat_compare_means(aes(group=Method)) + 
  #labs(x = "Sites", y = "Index", title = "none") + 
  #geom_jitter(width=.1) + 
  theme(plot.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 17, face = "bold", angle = 90, vjust = 0.5, hjust = 0.5),
        axis.text.x = element_blank(), 
        axis.text.y = element_text(size = 15, face = "plain", angle = 0, vjust = 0.5, hjust = 0.5),
        legend.title = element_text(size = 16, face = "bold", angle = 0, vjust = 0.5, hjust = 0),
        legend.text = element_text(size = 15, face = "plain", angle = 0, vjust = 0.5, hjust = 0),
        legend.key = element_rect(fill = 'transparent'),
        legend.position = 'right',
        legend.key.size=unit(0.8,'cm'),
        legend.key.width=unit(1.2,'cm'),
        legend.spacing.y = unit(0.5,"cm"),
        plot.margin = unit(c(1, 1, 1, 1),'cm'),
        strip.text.y = element_text(size=15,face = "bold"),
        strip.text.x = element_text(size=15,face = "bold"),
        panel.margin=unit(0.7,"cm"))
if(do.write){
  ggsave(width=12,height=20,filename="Richness-sites-methods.pdf")
}
```